# Generated by Django 3.0 on 2020-10-20 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201020_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='acitive',
            new_name='active',
        ),
    ]
